export { default as navLogo } from "../assets/images/header/headerLogo.svg"
export { default as navUser } from "../assets/images/header/avatar.svg"
export { default as headerImage } from "../assets/images/header/header.png"
export { default as headerLocation } from "../assets/images/header/location.svg"
export { default as headerBicycle } from "../assets/images/header/bicycle.svg"
export { default as headerCalendar } from "../assets/images/header/calendar.svg"
export { default as headerGuess } from "../assets/images/header/guess.svg"
export { default as headerSearch }from "../assets/images/header/search.svg"
export { default as introImg1 }from "../assets/images/main/BigSur.png"
export { default as introImg2 }from "../assets/images/main/Prescott.png"
export { default as introImg3 }from "../assets/images/main/FortMayers.png"
export { default as introImg4 }from "../assets/images/main/Tucson.png"
export { default as introImg5 }from "../assets/images/main/St.Joseph.png"
export { default as introImg6 }from "../assets/images/main/Madrid.png"
export { default as rightArrow }from "../assets/images/main/arrowRight.svg"
export { default as pinLocation }from "../assets/images/main/pin.svg"
export { default as fullStar }from "../assets/images/main/fullStar.svg"
export { default as fourStar }from "../assets/images/main/fourStar.svg"
export { default as threeStar }from "../assets/images/main/threeStar.svg"
export { default as hotel1Image }from "../assets/images/main/hotel1.png"
export { default as hotel2Image }from "../assets/images/main/hotel2.png"
export { default as hotel3Image }from "../assets/images/main/hotel3.png"
export { default as hotel4Image }from "../assets/images/main/hotel4.png"
export { default as iceCream }from "../assets/images/main/ice-cream.png"
export { default as brooklnyBridge }from "../assets/images/main/bridge.png"
export { default as calendarIcon }from "../assets/images/main/claendarIcon.svg"
export { default as userIcon }from "../assets/images/main/userIcon.svg"
export { default as messageIcon }from "../assets/images/main/chatIcon.svg"
export { default as sailingImg }from "../assets/images/main/sailing.png"
export { default as climbingImg }from "../assets/images/main/climbing.png"
export { default as skiingImg }from "../assets/images/main/skiing.png"
export { default as hikingImg }from "../assets/images/main/hiking.png"
export { default as aboutImg }from "../assets/images/main/aboutUs.png"
export { default as footerLogo }from "../assets/images/footer/footerLogo.svg"
export { default as facebook }from "../assets/images/footer/facebook.svg"
export { default as twitter }from "../assets/images/footer/twitter.svg"
export { default as instagram }from "../assets/images/footer/instagram.svg"
export { default as ftrArrowRight }from "../assets/images/footer/footerArrowRight.svg"
export { default as mailIcon}from "../assets/images/footer/mail.svg"